Desafio de projeto/blog/config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  root 'livros#index'
  resources :livros
  get "/articles", to: "articles#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Desafio de projeto/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Desafio de projeto/blog/app/models/livro.rb
class Livro < ApplicationRecord
      validates :title, :author, :rating, :description, presence: true
end

Desafio de projeto/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

Desafio de projeto/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

Desafio de projeto/blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

Desafio de projeto/blog/app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: %i[ show edit update destroy ]

  # GET /livros or /livros.json
  def index
    @livros = Livro.all
  end

  # GET /livros/1 or /livros/1.json
  def show
  end

  # GET /livros/new
  def new
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
  end

  # POST /livros or /livros.json
  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to @livro, notice: "Livro was successfully created." }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livros/1 or /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to @livro, notice: "Livro was successfully updated." }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1 or /livros/1.json
  def destroy
    @livro.destroy!

    respond_to do |format|
      format.html { redirect_to livros_path, status: :see_other, notice: "Livro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def livro_params
      params.require(:livro).permit(:title, :author, :rating, :description)
    end
end

Desafio de projeto/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Desafio de projeto/blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

Desafio de projeto/blog/app/helpers/home_helper.rb
module HomeHelper
end

Desafio de projeto/blog/app/helpers/livros_helper.rb
module LivrosHelper
end

Desafio de projeto/blog/app/views/articles/index.html.erb
<h1>Hello, Rails!</h1>

Desafio de projeto/blog/app/views/home/index.html.erb
<h1>Resenha e avaliação literária</h1>
<p>Find me in app/views/home/index.html.erb</p>

Desafio de projeto/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Desafio de projeto/blog/app/views/livros/_form.html.erb
<%= form_with(model: livro) do |form| %>
  <% if livro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(livro.errors.count, "error") %> prohibited this livro from being saved:</h2>

      <ul>
        <% livro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.number_field :rating %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Desafio de projeto/blog/app/views/livros/_livro.html.erb
<div id="<%= dom_id livro %>">
  <p>
    <strong>Title:</strong>
    <%= livro.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= livro.author %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= livro.rating %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= livro.description %>
  </p>

</div>

Desafio de projeto/blog/app/views/livros/edit.html.erb
<% content_for :title, "Editing livro" %>

<h1>Editing livro</h1>

<%= render "form", livro: @livro %>

<br>

<div>
  <%= link_to "Show this livro", @livro %> |
  <%= link_to "Back to livros", livros_path %>
</div>

Desafio de projeto/blog/app/views/livros/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Livros" %>

<h1>Resenha e avaliação literária</h1>

<div id="livros">
  <% @livros.each do |livro| %>
    <%= render livro %>
    <p>
      <%= link_to "Show this livro", livro %>
    </p>
  <% end %>
</div>

<%= link_to "New livro", new_livro_path %>

Desafio de projeto/blog/app/views/livros/new.html.erb
<% content_for :title, "New livro" %>

<h1>New livro</h1>

<%= render "form", livro: @livro %>

<br>

<div>
  <%= link_to "Back to livros", livros_path %>
</div>

Desafio de projeto/blog/app/views/livros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @livro %>

<div>
  <%= link_to "Edit this livro", edit_livro_path(@livro) %> |
  <%= link_to "Back to livros", livros_path %>

  <%= button_to "Destroy this livro", @livro, method: :delete %>
</div>